### PR TITLE
added capability to set forecastSelection=strict

### LINKED ISSUE #151: run only specified FORECASTCYCLES
When the ASGS starts or restarts, it automatically detects the latest meteorological data and runs the latest forecast, even if that forecast was not specified by the Operator. Need to add ability for the Operator to specify strict adherence to running forecast cycles, even if that means going back in time and running an older forecast cycle rather than the latest.

### PR DESCRIPTION
**Pull request by jasonfleming**
Resolves #151

### CODE REVIEW

**Review by wwlwpd — CHANGES_REQUESTED** [review]
I might have applied these PRs in the wrong order, but if you don't
mind please rebase this branch/PR on current master. I tried to figure
out which changes to apply myself; but I was afraid of undoing some of
your work while trying to also prevent this file from travelling "back
in time".

Additional comments for future PRs:

1. please make sure trailing white spaces are removed (`git diff` shows
these as big red blocks

2. make sure all PRs are up to date with the latest master; that might
not have prevented this current situation which is likely mostly my fault;
it will reduce the complication of the PRs, though

Thanks and sorry!

**Comment by jasonfleming** [comment]
Hey Brett, thank you for the review and comments, I have added your PR-related guidance to our fledgling ASGS wiki. :-) I kind of went crazy with these PRs. I have now merged the latest master into the issue-151 branch, I hope this makes things cleaner. I did not see the trailing whitespace in git diff, so I enabled a feature in Visual Studio Code that will trim that automatically for me when I save files. I also invoked this trimming specifically for get_nam.pl and asgs_main.sh. Please have a look to see if this PR is workable now.

**Comment by wwlwpd** [comment]
There was a merge conflict with the master branch,
and it seemed straightforward enough to resolve.

However, I'd like for you to review the result of the
conflict resolution; if it looks fine to you, feel
free the merge it. I can also do it but it's up to you.

The "conflicts" resolved were in asgs_main.sh, and I
just preferred in all cases the changes that were present
in the feature branch.﻿

**Review by wwlwpd — APPROVED** [review]
Looks good to me. I really focused on the syntax aspect
for the shell and Perl; Merging.﻿

**Pull request merged**
